# Generated by Django 4.2.2 on 2024-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Почта клиента')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия клиента')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество клиента')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата добавления клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время попытки рассылки')),
                ('successful_attempt', models.BooleanField(verbose_name='Попытка успешная')),
                ('error_at', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет в случае ошибки попытки')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей попытки рассылки')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время отправки первой рассылки')),
                ('period', models.CharField(choices=[('days', 'Ежедневная рассылка'), ('weeks', 'Еженедельная рассылка'), ('months', 'Ежемесячная рассылка')], verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'Рассылка создана'), ('active', 'Рассылка запущена'), ('closed', 'Рассылка завершена')], default='created', verbose_name='Статус рассылки')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
