# Generated by Django 4.2.2 on 2024-11-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('can_disable_mailings', 'can disable mailings'), ('can_view_any_mailings', 'can view any mailings lists')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
